import type { PublicQuestion } from "./types.ts";
import publicBundleData from "../../content/generated/public-bundle.json";
import { questionsForDate as pureQuestionsForDate, puzzleNumberForDate as purePuzzleNumberForDate } from "./daily.ts";

interface PublicBundle {
  questions: PublicQuestion[];
  launchDate: string;
  schedule: Record<string, string[]>;
}

// Generated by tools/bundleContent.ts (run as part of `npm run build`) from
// content/questions/*.json with value/funFact/source stripped out — the
// true answer never ships in this bundle. See src/ui/reveal.ts and
// worker/index.ts's /api/reveal for where that data actually comes from.
const bundle = publicBundleData as PublicBundle;

export const questionBank: PublicQuestion[] = bundle.questions;

export const questionsById: Map<string, PublicQuestion> = new Map(questionBank.map((q) => [q.id, q]));

export const schedule: Record<string, string[]> = bundle.schedule;

export const launchDate: string = bundle.launchDate;

export function getQuestion(id: string): PublicQuestion {
  const q = questionsById.get(id);
  if (!q) throw new Error(`Unknown question id: ${id}`);
  return q;
}

/** Bound convenience wrapper over the pure daily.ts resolver, using this app's loaded bank. */
export function questionsForDate(dateStr: string): PublicQuestion[] {
  return pureQuestionsForDate(dateStr, schedule, questionBank, questionsById);
}

export function puzzleNumberForDate(dateStr: string): number {
  return purePuzzleNumberForDate(dateStr, launchDate);
}
